version: "3"

services:
  db:
    image: mariadb:latest
    volumes:
      - ./db/data_dump:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass

  py-srv:
    build: py-srv
    command: python app.py
    ports:
      - "443:443"

  py-test-srv:
    build:
      context: py-test-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:3306,py-srv:443
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-srv
    links:
      - "py-srv:py-srv"

